-- Data migration script to move user settings to separate table
-- Step 1: Create UserSettings table (this will be done by Prisma migration)
-- Step 2: Copy data from users table to user_settings table
-- Step 3: Drop columns from users table (this will be done by Prisma migration)

-- Copy user data to user_settings table
INSERT INTO user_settings (
  id, 
  userId, 
  maxUploads, 
  maxFileSize, 
  maxStorageLimit, 
  storageUsed,
  embedTitle,
  embedDescription,
  embedColor,
  embedAuthor,
  embedFooter,
  showFileInfo,
  showUploadDate,
  showUserStats,
  customDomain,
  uploadDomainId,
  customSubdomain,
  useCustomWords,
  defaultExpirationDays,
  defaultMaxViews,
  globalParticleConfig,
  bioUsername,
  bioDisplayName,
  bioDescription,
  bioProfileImage,
  bioBackgroundImage,
  bioBackgroundColor,
  bioTextColor,
  bioAccentColor,
  bioCustomCss,
  bioSpotifyTrack,
  bioIsPublic,
  bioViews,
  bioLastViewed,
  bioGradientConfig,
  bioParticleConfig,
  bioDiscordUserId,
  bioShowDiscord,
  bioDiscordConfig,
  maxBioLinks,
  maxUsernameLength,
  maxDisplayNameLength,
  maxDescriptionLength,
  maxUrlLength,
  maxLinkTitleLength,
  maxIconLength,
  createdAt,
  updatedAt
)
SELECT 
  lower(hex(randomblob(12))) as id, -- Generate new ID for settings
  id as userId,
  maxUploads,
  maxFileSize,
  maxStorageLimit,
  storageUsed,
  embedTitle,
  embedDescription,
  embedColor,
  embedAuthor,
  embedFooter,
  showFileInfo,
  showUploadDate,
  showUserStats,
  customDomain,
  uploadDomainId,
  customSubdomain,
  useCustomWords,
  defaultExpirationDays,
  defaultMaxViews,
  globalParticleConfig,
  bioUsername,
  bioDisplayName,
  bioDescription,
  bioProfileImage,
  bioBackgroundImage,
  bioBackgroundColor,
  bioTextColor,
  bioAccentColor,
  bioCustomCss,
  bioSpotifyTrack,
  bioIsPublic,
  bioViews,
  bioLastViewed,
  bioGradientConfig,
  bioParticleConfig,
  bioDiscordUserId,
  bioShowDiscord,
  bioDiscordConfig,
  maxBioLinks,
  maxUsernameLength,
  maxDisplayNameLength,
  maxDescriptionLength,
  maxUrlLength,
  maxLinkTitleLength,
  maxIconLength,
  createdAt,
  updatedAt
FROM users;
