-- AlterTable
ALTER TABLE "users" ADD COLUMN "maxBioLinks" INTEGER DEFAULT 10;
ALTER TABLE "users" ADD COLUMN "maxDescriptionLength" INTEGER DEFAULT 1000;
ALTER TABLE "users" ADD COLUMN "maxDisplayNameLength" INTEGER DEFAULT 20;
ALTER TABLE "users" ADD COLUMN "maxIconLength" INTEGER DEFAULT 20;
ALTER TABLE "users" ADD COLUMN "maxLinkTitleLength" INTEGER DEFAULT 50;
ALTER TABLE "users" ADD COLUMN "maxUrlLength" INTEGER DEFAULT 200;
ALTER TABLE "users" ADD COLUMN "maxUsernameLength" INTEGER DEFAULT 20;
